//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input/mdl_swg_msg.proto
namespace datayes.mdl.mdl_swg_pbmsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"float_3")]
  public partial class float_3 : global::ProtoBuf.IExtensible
  {
    public float_3() {}
    
    private int _Value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Value
    {
      get { return _Value; }
      set { _Value = value; }
    }
    private uint _DecimalShift = (uint)1000;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"DecimalShift", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)1000)]
    public uint DecimalShift
    {
      get { return _DecimalShift; }
      set { _DecimalShift = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Index")]
  public partial class Index : global::ProtoBuf.IExtensible
  {
    public Index() {}
    
    private string _SecurityID = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"SecurityID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SecurityID
    {
      get { return _SecurityID; }
      set { _SecurityID = value; }
    }
    private string _SecurityName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SecurityName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SecurityName
    {
      get { return _SecurityName; }
      set { _SecurityName = value; }
    }
    private datayes.mdl.mdl_swg_pbmsg.float_3 _PreCloPrice = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"PreCloPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_swg_pbmsg.float_3 PreCloPrice
    {
      get { return _PreCloPrice; }
      set { _PreCloPrice = value; }
    }
    private datayes.mdl.mdl_swg_pbmsg.float_3 _OpenPrice = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"OpenPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_swg_pbmsg.float_3 OpenPrice
    {
      get { return _OpenPrice; }
      set { _OpenPrice = value; }
    }
    private ulong _Turnover = default(ulong);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Turnover", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Turnover
    {
      get { return _Turnover; }
      set { _Turnover = value; }
    }
    private datayes.mdl.mdl_swg_pbmsg.float_3 _HighPrice = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"HighPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_swg_pbmsg.float_3 HighPrice
    {
      get { return _HighPrice; }
      set { _HighPrice = value; }
    }
    private datayes.mdl.mdl_swg_pbmsg.float_3 _LowPrice = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"LowPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_swg_pbmsg.float_3 LowPrice
    {
      get { return _LowPrice; }
      set { _LowPrice = value; }
    }
    private datayes.mdl.mdl_swg_pbmsg.float_3 _LastPrice = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"LastPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_swg_pbmsg.float_3 LastPrice
    {
      get { return _LastPrice; }
      set { _LastPrice = value; }
    }
    private datayes.mdl.mdl_swg_pbmsg.float_3 _Ratio = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"Ratio", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_swg_pbmsg.float_3 Ratio
    {
      get { return _Ratio; }
      set { _Ratio = value; }
    }
    private ulong _Volume = default(ulong);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"Volume", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Volume
    {
      get { return _Volume; }
      set { _Volume = value; }
    }
    private ulong _BidVolume123 = default(ulong);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"BidVolume123", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong BidVolume123
    {
      get { return _BidVolume123; }
      set { _BidVolume123 = value; }
    }
    private datayes.mdl.mdl_swg_pbmsg.float_3 _BidPrice2 = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"BidPrice2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_swg_pbmsg.float_3 BidPrice2
    {
      get { return _BidPrice2; }
      set { _BidPrice2 = value; }
    }
    private ulong _BidVolume2 = default(ulong);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"BidVolume2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong BidVolume2
    {
      get { return _BidVolume2; }
      set { _BidVolume2 = value; }
    }
    private datayes.mdl.mdl_swg_pbmsg.float_3 _BidPrice3 = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"BidPrice3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_swg_pbmsg.float_3 BidPrice3
    {
      get { return _BidPrice3; }
      set { _BidPrice3 = value; }
    }
    private ulong _BidVolume3 = default(ulong);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"BidVolume3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong BidVolume3
    {
      get { return _BidVolume3; }
      set { _BidVolume3 = value; }
    }
    private ulong _AskVolume123 = default(ulong);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"AskVolume123", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong AskVolume123
    {
      get { return _AskVolume123; }
      set { _AskVolume123 = value; }
    }
    private datayes.mdl.mdl_swg_pbmsg.float_3 _AskPrice2 = null;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"AskPrice2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_swg_pbmsg.float_3 AskPrice2
    {
      get { return _AskPrice2; }
      set { _AskPrice2 = value; }
    }
    private ulong _AskVolume2 = default(ulong);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"AskVolume2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong AskVolume2
    {
      get { return _AskVolume2; }
      set { _AskVolume2 = value; }
    }
    private datayes.mdl.mdl_swg_pbmsg.float_3 _AskPrice3 = null;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"AskPrice3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_swg_pbmsg.float_3 AskPrice3
    {
      get { return _AskPrice3; }
      set { _AskPrice3 = value; }
    }
    private ulong _AskVolume3 = default(ulong);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"AskVolume3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong AskVolume3
    {
      get { return _AskVolume3; }
      set { _AskVolume3 = value; }
    }
    private uint _UpdateTime = default(uint);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"UpdateTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint UpdateTime
    {
      get { return _UpdateTime; }
      set { _UpdateTime = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"MID")]
    public enum MID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MessageID", Value=1)]
      MessageID = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SID")]
    public enum SID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceID", Value=12)]
      ServiceID = 12
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"VID")]
    public enum VID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceVersion", Value=101)]
      ServiceVersion = 101
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MDLSWGServiceVersion")]
    public enum MDLSWGServiceVersion
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MDLVID_MDL_SWG", Value=101)]
      MDLVID_MDL_SWG = 101
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MDLSWGMessageID")]
    public enum MDLSWGMessageID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MDLMID_MDL_SWG_Index", Value=1)]
      MDLMID_MDL_SWG_Index = 1
    }
  
}