//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input/mdl_czce_msg.proto
namespace datayes.mdl.mdl_czce_pbmsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"double_3")]
  public partial class double_3 : global::ProtoBuf.IExtensible
  {
    public double_3() {}
    
    private long _Value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long Value
    {
      get { return _Value; }
      set { _Value = value; }
    }
    private uint _DecimalShift = (uint)1000;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"DecimalShift", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)1000)]
    public uint DecimalShift
    {
      get { return _DecimalShift; }
      set { _DecimalShift = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTPFuture")]
  public partial class CTPFuture : global::ProtoBuf.IExtensible
  {
    public CTPFuture() {}
    
    private string _InstruID = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"InstruID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string InstruID
    {
      get { return _InstruID; }
      set { _InstruID = value; }
    }
    private datayes.mdl.mdl_czce_pbmsg.double_3 _LastPrice = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"LastPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_czce_pbmsg.double_3 LastPrice
    {
      get { return _LastPrice; }
      set { _LastPrice = value; }
    }
    private datayes.mdl.mdl_czce_pbmsg.double_3 _PreSetPrice = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"PreSetPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_czce_pbmsg.double_3 PreSetPrice
    {
      get { return _PreSetPrice; }
      set { _PreSetPrice = value; }
    }
    private datayes.mdl.mdl_czce_pbmsg.double_3 _OpenPrice = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"OpenPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_czce_pbmsg.double_3 OpenPrice
    {
      get { return _OpenPrice; }
      set { _OpenPrice = value; }
    }
    private datayes.mdl.mdl_czce_pbmsg.double_3 _HighPrice = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"HighPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_czce_pbmsg.double_3 HighPrice
    {
      get { return _HighPrice; }
      set { _HighPrice = value; }
    }
    private datayes.mdl.mdl_czce_pbmsg.double_3 _LowPrice = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"LowPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_czce_pbmsg.double_3 LowPrice
    {
      get { return _LowPrice; }
      set { _LowPrice = value; }
    }
    private datayes.mdl.mdl_czce_pbmsg.double_3 _Turnover = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"Turnover", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_czce_pbmsg.double_3 Turnover
    {
      get { return _Turnover; }
      set { _Turnover = value; }
    }
    private datayes.mdl.mdl_czce_pbmsg.double_3 _OpenInt = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"OpenInt", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_czce_pbmsg.double_3 OpenInt
    {
      get { return _OpenInt; }
      set { _OpenInt = value; }
    }
    private datayes.mdl.mdl_czce_pbmsg.double_3 _SetPrice = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"SetPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_czce_pbmsg.double_3 SetPrice
    {
      get { return _SetPrice; }
      set { _SetPrice = value; }
    }
    private datayes.mdl.mdl_czce_pbmsg.double_3 _ULimitPrice = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"ULimitPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_czce_pbmsg.double_3 ULimitPrice
    {
      get { return _ULimitPrice; }
      set { _ULimitPrice = value; }
    }
    private datayes.mdl.mdl_czce_pbmsg.double_3 _LLimitPrice = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"LLimitPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_czce_pbmsg.double_3 LLimitPrice
    {
      get { return _LLimitPrice; }
      set { _LLimitPrice = value; }
    }
    private uint _TradDay = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"TradDay", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint TradDay
    {
      get { return _TradDay; }
      set { _TradDay = value; }
    }
    private datayes.mdl.mdl_czce_pbmsg.double_3 _PreCloPrice = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"PreCloPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_czce_pbmsg.double_3 PreCloPrice
    {
      get { return _PreCloPrice; }
      set { _PreCloPrice = value; }
    }
    private int _Volume = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"Volume", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Volume
    {
      get { return _Volume; }
      set { _Volume = value; }
    }
    private datayes.mdl.mdl_czce_pbmsg.double_3 _ClosePrice = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"ClosePrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_czce_pbmsg.double_3 ClosePrice
    {
      get { return _ClosePrice; }
      set { _ClosePrice = value; }
    }
    private datayes.mdl.mdl_czce_pbmsg.double_3 _PreDelta = null;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"PreDelta", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_czce_pbmsg.double_3 PreDelta
    {
      get { return _PreDelta; }
      set { _PreDelta = value; }
    }
    private datayes.mdl.mdl_czce_pbmsg.double_3 _CurrDelta = null;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"CurrDelta", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_czce_pbmsg.double_3 CurrDelta
    {
      get { return _CurrDelta; }
      set { _CurrDelta = value; }
    }
    private uint _UpdateTime = default(uint);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"UpdateTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint UpdateTime
    {
      get { return _UpdateTime; }
      set { _UpdateTime = value; }
    }
    private datayes.mdl.mdl_czce_pbmsg.double_3 _PreOpenInt = null;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"PreOpenInt", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_czce_pbmsg.double_3 PreOpenInt
    {
      get { return _PreOpenInt; }
      set { _PreOpenInt = value; }
    }
    private datayes.mdl.mdl_czce_pbmsg.double_3 _BidPrice1 = null;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"BidPrice1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_czce_pbmsg.double_3 BidPrice1
    {
      get { return _BidPrice1; }
      set { _BidPrice1 = value; }
    }
    private int _BidVolume1 = default(int);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"BidVolume1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int BidVolume1
    {
      get { return _BidVolume1; }
      set { _BidVolume1 = value; }
    }
    private datayes.mdl.mdl_czce_pbmsg.double_3 _AskPrice1 = null;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"AskPrice1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_czce_pbmsg.double_3 AskPrice1
    {
      get { return _AskPrice1; }
      set { _AskPrice1 = value; }
    }
    private int _AskVolume1 = default(int);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"AskVolume1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int AskVolume1
    {
      get { return _AskVolume1; }
      set { _AskVolume1 = value; }
    }
    private datayes.mdl.mdl_czce_pbmsg.double_3 _BidPrice2 = null;
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"BidPrice2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_czce_pbmsg.double_3 BidPrice2
    {
      get { return _BidPrice2; }
      set { _BidPrice2 = value; }
    }
    private int _BidVolume2 = default(int);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"BidVolume2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int BidVolume2
    {
      get { return _BidVolume2; }
      set { _BidVolume2 = value; }
    }
    private datayes.mdl.mdl_czce_pbmsg.double_3 _AskPrice2 = null;
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"AskPrice2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_czce_pbmsg.double_3 AskPrice2
    {
      get { return _AskPrice2; }
      set { _AskPrice2 = value; }
    }
    private int _AskVolume2 = default(int);
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"AskVolume2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int AskVolume2
    {
      get { return _AskVolume2; }
      set { _AskVolume2 = value; }
    }
    private datayes.mdl.mdl_czce_pbmsg.double_3 _BidPrice3 = null;
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"BidPrice3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_czce_pbmsg.double_3 BidPrice3
    {
      get { return _BidPrice3; }
      set { _BidPrice3 = value; }
    }
    private int _BidVolume3 = default(int);
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"BidVolume3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int BidVolume3
    {
      get { return _BidVolume3; }
      set { _BidVolume3 = value; }
    }
    private datayes.mdl.mdl_czce_pbmsg.double_3 _AskPrice3 = null;
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"AskPrice3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_czce_pbmsg.double_3 AskPrice3
    {
      get { return _AskPrice3; }
      set { _AskPrice3 = value; }
    }
    private int _AskVolume3 = default(int);
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"AskVolume3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int AskVolume3
    {
      get { return _AskVolume3; }
      set { _AskVolume3 = value; }
    }
    private datayes.mdl.mdl_czce_pbmsg.double_3 _BidPrice4 = null;
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"BidPrice4", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_czce_pbmsg.double_3 BidPrice4
    {
      get { return _BidPrice4; }
      set { _BidPrice4 = value; }
    }
    private int _BidVolume4 = default(int);
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"BidVolume4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int BidVolume4
    {
      get { return _BidVolume4; }
      set { _BidVolume4 = value; }
    }
    private datayes.mdl.mdl_czce_pbmsg.double_3 _AskPrice4 = null;
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"AskPrice4", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_czce_pbmsg.double_3 AskPrice4
    {
      get { return _AskPrice4; }
      set { _AskPrice4 = value; }
    }
    private int _AskVolume4 = default(int);
    [global::ProtoBuf.ProtoMember(35, IsRequired = false, Name=@"AskVolume4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int AskVolume4
    {
      get { return _AskVolume4; }
      set { _AskVolume4 = value; }
    }
    private datayes.mdl.mdl_czce_pbmsg.double_3 _BidPrice5 = null;
    [global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"BidPrice5", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_czce_pbmsg.double_3 BidPrice5
    {
      get { return _BidPrice5; }
      set { _BidPrice5 = value; }
    }
    private int _BidVolume5 = default(int);
    [global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"BidVolume5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int BidVolume5
    {
      get { return _BidVolume5; }
      set { _BidVolume5 = value; }
    }
    private datayes.mdl.mdl_czce_pbmsg.double_3 _AskPrice5 = null;
    [global::ProtoBuf.ProtoMember(38, IsRequired = false, Name=@"AskPrice5", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_czce_pbmsg.double_3 AskPrice5
    {
      get { return _AskPrice5; }
      set { _AskPrice5 = value; }
    }
    private int _AskVolume5 = default(int);
    [global::ProtoBuf.ProtoMember(39, IsRequired = false, Name=@"AskVolume5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int AskVolume5
    {
      get { return _AskVolume5; }
      set { _AskVolume5 = value; }
    }
    private datayes.mdl.mdl_czce_pbmsg.double_3 _AveragePrice = null;
    [global::ProtoBuf.ProtoMember(40, IsRequired = false, Name=@"AveragePrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_czce_pbmsg.double_3 AveragePrice
    {
      get { return _AveragePrice; }
      set { _AveragePrice = value; }
    }
    private uint _ActionDay = default(uint);
    [global::ProtoBuf.ProtoMember(41, IsRequired = false, Name=@"ActionDay", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ActionDay
    {
      get { return _ActionDay; }
      set { _ActionDay = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"MID")]
    public enum MID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MessageID", Value=1)]
      MessageID = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SID")]
    public enum SID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceID", Value=8)]
      ServiceID = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"VID")]
    public enum VID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceVersion", Value=101)]
      ServiceVersion = 101
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MDLCZCEServiceVersion")]
    public enum MDLCZCEServiceVersion
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MDLVID_MDL_CZCE", Value=101)]
      MDLVID_MDL_CZCE = 101
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MDLCZCEMessageID")]
    public enum MDLCZCEMessageID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MDLMID_MDL_CZCE_CTPFuture", Value=1)]
      MDLMID_MDL_CZCE_CTPFuture = 1
    }
  
}