//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input/mdl_shl2_msg.proto
namespace datayes.mdl.mdl_shl2_pbmsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"float_3")]
  public partial class float_3 : global::ProtoBuf.IExtensible
  {
    public float_3() {}
    
    private int _Value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Value
    {
      get { return _Value; }
      set { _Value = value; }
    }
    private uint _DecimalShift = (uint)1000;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"DecimalShift", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)1000)]
    public uint DecimalShift
    {
      get { return _DecimalShift; }
      set { _DecimalShift = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"double_3")]
  public partial class double_3 : global::ProtoBuf.IExtensible
  {
    public double_3() {}
    
    private long _Value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long Value
    {
      get { return _Value; }
      set { _Value = value; }
    }
    private uint _DecimalShift = (uint)1000;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"DecimalShift", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)1000)]
    public uint DecimalShift
    {
      get { return _DecimalShift; }
      set { _DecimalShift = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"double_5")]
  public partial class double_5 : global::ProtoBuf.IExtensible
  {
    public double_5() {}
    
    private long _Value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long Value
    {
      get { return _Value; }
      set { _Value = value; }
    }
    private uint _DecimalShift = (uint)100000;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"DecimalShift", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)100000)]
    public uint DecimalShift
    {
      get { return _DecimalShift; }
      set { _DecimalShift = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"float_4")]
  public partial class float_4 : global::ProtoBuf.IExtensible
  {
    public float_4() {}
    
    private int _Value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Value
    {
      get { return _Value; }
      set { _Value = value; }
    }
    private uint _DecimalShift = (uint)10000;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"DecimalShift", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)10000)]
    public uint DecimalShift
    {
      get { return _DecimalShift; }
      set { _DecimalShift = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"double_1")]
  public partial class double_1 : global::ProtoBuf.IExtensible
  {
    public double_1() {}
    
    private long _Value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long Value
    {
      get { return _Value; }
      set { _Value = value; }
    }
    private uint _DecimalShift = (uint)10;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"DecimalShift", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)10)]
    public uint DecimalShift
    {
      get { return _DecimalShift; }
      set { _DecimalShift = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"double_4")]
  public partial class double_4 : global::ProtoBuf.IExtensible
  {
    public double_4() {}
    
    private long _Value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long Value
    {
      get { return _Value; }
      set { _Value = value; }
    }
    private uint _DecimalShift = (uint)10000;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"DecimalShift", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)10000)]
    public uint DecimalShift
    {
      get { return _DecimalShift; }
      set { _DecimalShift = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"double_2")]
  public partial class double_2 : global::ProtoBuf.IExtensible
  {
    public double_2() {}
    
    private long _Value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long Value
    {
      get { return _Value; }
      set { _Value = value; }
    }
    private uint _DecimalShift = (uint)100;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"DecimalShift", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)100)]
    public uint DecimalShift
    {
      get { return _DecimalShift; }
      set { _DecimalShift = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SHL1Stock")]
  public partial class SHL1Stock : global::ProtoBuf.IExtensible
  {
    public SHL1Stock() {}
    
    private string _SecurityID = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"SecurityID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SecurityID
    {
      get { return _SecurityID; }
      set { _SecurityID = value; }
    }
    private string _SecurityName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SecurityName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SecurityName
    {
      get { return _SecurityName; }
      set { _SecurityName = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _PreCloPrice = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"PreCloPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 PreCloPrice
    {
      get { return _PreCloPrice; }
      set { _PreCloPrice = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _OpenPrice = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"OpenPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 OpenPrice
    {
      get { return _OpenPrice; }
      set { _OpenPrice = value; }
    }
    private long _Turnover = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Turnover", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long Turnover
    {
      get { return _Turnover; }
      set { _Turnover = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _HighPrice = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"HighPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 HighPrice
    {
      get { return _HighPrice; }
      set { _HighPrice = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _LowPrice = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"LowPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 LowPrice
    {
      get { return _LowPrice; }
      set { _LowPrice = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _LastPrice = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"LastPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 LastPrice
    {
      get { return _LastPrice; }
      set { _LastPrice = value; }
    }
    private ulong _Volume = default(ulong);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"Volume", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Volume
    {
      get { return _Volume; }
      set { _Volume = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _PE = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"PE", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 PE
    {
      get { return _PE; }
      set { _PE = value; }
    }
    private ulong _BidVolume1 = default(ulong);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"BidVolume1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong BidVolume1
    {
      get { return _BidVolume1; }
      set { _BidVolume1 = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _BidPrice1 = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"BidPrice1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 BidPrice1
    {
      get { return _BidPrice1; }
      set { _BidPrice1 = value; }
    }
    private ulong _BidVolume2 = default(ulong);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"BidVolume2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong BidVolume2
    {
      get { return _BidVolume2; }
      set { _BidVolume2 = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _BidPrice2 = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"BidPrice2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 BidPrice2
    {
      get { return _BidPrice2; }
      set { _BidPrice2 = value; }
    }
    private ulong _BidVolume3 = default(ulong);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"BidVolume3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong BidVolume3
    {
      get { return _BidVolume3; }
      set { _BidVolume3 = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _BidPrice3 = null;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"BidPrice3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 BidPrice3
    {
      get { return _BidPrice3; }
      set { _BidPrice3 = value; }
    }
    private ulong _BidVolume4 = default(ulong);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"BidVolume4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong BidVolume4
    {
      get { return _BidVolume4; }
      set { _BidVolume4 = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _BidPrice4 = null;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"BidPrice4", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 BidPrice4
    {
      get { return _BidPrice4; }
      set { _BidPrice4 = value; }
    }
    private ulong _BidVolume5 = default(ulong);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"BidVolume5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong BidVolume5
    {
      get { return _BidVolume5; }
      set { _BidVolume5 = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _BidPrice5 = null;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"BidPrice5", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 BidPrice5
    {
      get { return _BidPrice5; }
      set { _BidPrice5 = value; }
    }
    private ulong _AskVolume1 = default(ulong);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"AskVolume1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong AskVolume1
    {
      get { return _AskVolume1; }
      set { _AskVolume1 = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _AskPrice1 = null;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"AskPrice1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 AskPrice1
    {
      get { return _AskPrice1; }
      set { _AskPrice1 = value; }
    }
    private ulong _AskVolume2 = default(ulong);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"AskVolume2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong AskVolume2
    {
      get { return _AskVolume2; }
      set { _AskVolume2 = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _AskPrice2 = null;
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"AskPrice2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 AskPrice2
    {
      get { return _AskPrice2; }
      set { _AskPrice2 = value; }
    }
    private ulong _AskVolume3 = default(ulong);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"AskVolume3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong AskVolume3
    {
      get { return _AskVolume3; }
      set { _AskVolume3 = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _AskPrice3 = null;
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"AskPrice3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 AskPrice3
    {
      get { return _AskPrice3; }
      set { _AskPrice3 = value; }
    }
    private ulong _AskVolume4 = default(ulong);
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"AskVolume4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong AskVolume4
    {
      get { return _AskVolume4; }
      set { _AskVolume4 = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _AskPrice4 = null;
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"AskPrice4", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 AskPrice4
    {
      get { return _AskPrice4; }
      set { _AskPrice4 = value; }
    }
    private ulong _AskVolume5 = default(ulong);
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"AskVolume5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong AskVolume5
    {
      get { return _AskVolume5; }
      set { _AskVolume5 = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _AskPrice5 = null;
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"AskPrice5", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 AskPrice5
    {
      get { return _AskPrice5; }
      set { _AskPrice5 = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"MID")]
    public enum MID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MessageID", Value=2)]
      MessageID = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SID")]
    public enum SID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceID", Value=4)]
      ServiceID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"VID")]
    public enum VID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceVersion", Value=101)]
      ServiceVersion = 101
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SHL2Transaction")]
  public partial class SHL2Transaction : global::ProtoBuf.IExtensible
  {
    public SHL2Transaction() {}
    
    private int _DataStatus = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"DataStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int DataStatus
    {
      get { return _DataStatus; }
      set { _DataStatus = value; }
    }
    private int _TradeIndex = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"TradeIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int TradeIndex
    {
      get { return _TradeIndex; }
      set { _TradeIndex = value; }
    }
    private int _TradeChan = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"TradeChan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int TradeChan
    {
      get { return _TradeChan; }
      set { _TradeChan = value; }
    }
    private string _SecurityID = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"SecurityID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SecurityID
    {
      get { return _SecurityID; }
      set { _SecurityID = value; }
    }
    private uint _TradTime = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"TradTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint TradTime
    {
      get { return _TradTime; }
      set { _TradTime = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _TradPrice = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"TradPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 TradPrice
    {
      get { return _TradPrice; }
      set { _TradPrice = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_3 _TradVolume = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"TradVolume", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_3 TradVolume
    {
      get { return _TradVolume; }
      set { _TradVolume = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_5 _TradeMoney = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"TradeMoney", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_5 TradeMoney
    {
      get { return _TradeMoney; }
      set { _TradeMoney = value; }
    }
    private long _TradeBuyNo = default(long);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"TradeBuyNo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long TradeBuyNo
    {
      get { return _TradeBuyNo; }
      set { _TradeBuyNo = value; }
    }
    private long _TradeSellNo = default(long);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"TradeSellNo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long TradeSellNo
    {
      get { return _TradeSellNo; }
      set { _TradeSellNo = value; }
    }
    private string _TradeBSFlag = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"TradeBSFlag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string TradeBSFlag
    {
      get { return _TradeBSFlag; }
      set { _TradeBSFlag = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"MID")]
    public enum MID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MessageID", Value=3)]
      MessageID = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SID")]
    public enum SID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceID", Value=4)]
      ServiceID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"VID")]
    public enum VID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceVersion", Value=101)]
      ServiceVersion = 101
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SHL2MarketData")]
  public partial class SHL2MarketData : global::ProtoBuf.IExtensible
  {
    public SHL2MarketData() {}
    
    private uint _UpdateTime = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"UpdateTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint UpdateTime
    {
      get { return _UpdateTime; }
      set { _UpdateTime = value; }
    }
    private string _SecurityID = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SecurityID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SecurityID
    {
      get { return _SecurityID; }
      set { _SecurityID = value; }
    }
    private int _ImageStatus = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ImageStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ImageStatus
    {
      get { return _ImageStatus; }
      set { _ImageStatus = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _PreCloPrice = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"PreCloPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 PreCloPrice
    {
      get { return _PreCloPrice; }
      set { _PreCloPrice = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _OpenPrice = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"OpenPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 OpenPrice
    {
      get { return _OpenPrice; }
      set { _OpenPrice = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _HighPrice = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"HighPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 HighPrice
    {
      get { return _HighPrice; }
      set { _HighPrice = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _LowPrice = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"LowPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 LowPrice
    {
      get { return _LowPrice; }
      set { _LowPrice = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _LastPrice = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"LastPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 LastPrice
    {
      get { return _LastPrice; }
      set { _LastPrice = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _ClosePrice = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"ClosePrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 ClosePrice
    {
      get { return _ClosePrice; }
      set { _ClosePrice = value; }
    }
    private string _InstruStatus = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"InstruStatus", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string InstruStatus
    {
      get { return _InstruStatus; }
      set { _InstruStatus = value; }
    }
    private uint _TradNumber = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"TradNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint TradNumber
    {
      get { return _TradNumber; }
      set { _TradNumber = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_3 _TradVolume = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"TradVolume", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_3 TradVolume
    {
      get { return _TradVolume; }
      set { _TradVolume = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_5 _Turnover = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"Turnover", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_5 Turnover
    {
      get { return _Turnover; }
      set { _Turnover = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_3 _TotalBidVol = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"TotalBidVol", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_3 TotalBidVol
    {
      get { return _TotalBidVol; }
      set { _TotalBidVol = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _WAvgBidPri = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"WAvgBidPri", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 WAvgBidPri
    {
      get { return _WAvgBidPri; }
      set { _WAvgBidPri = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _AltWAvgBidPri = null;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"AltWAvgBidPri", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 AltWAvgBidPri
    {
      get { return _AltWAvgBidPri; }
      set { _AltWAvgBidPri = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_3 _TotalAskVol = null;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"TotalAskVol", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_3 TotalAskVol
    {
      get { return _TotalAskVol; }
      set { _TotalAskVol = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _WAvgAskPri = null;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"WAvgAskPri", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 WAvgAskPri
    {
      get { return _WAvgAskPri; }
      set { _WAvgAskPri = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _AltWAvgAskPri = null;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"AltWAvgAskPri", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 AltWAvgAskPri
    {
      get { return _AltWAvgAskPri; }
      set { _AltWAvgAskPri = value; }
    }
    private uint _EtfBuyNumber = default(uint);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"EtfBuyNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint EtfBuyNumber
    {
      get { return _EtfBuyNumber; }
      set { _EtfBuyNumber = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_3 _EtfBuyVolume = null;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"EtfBuyVolume", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_3 EtfBuyVolume
    {
      get { return _EtfBuyVolume; }
      set { _EtfBuyVolume = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_5 _EtfBuyMoney = null;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"EtfBuyMoney", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_5 EtfBuyMoney
    {
      get { return _EtfBuyMoney; }
      set { _EtfBuyMoney = value; }
    }
    private uint _EtfSellNumber = default(uint);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"EtfSellNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint EtfSellNumber
    {
      get { return _EtfSellNumber; }
      set { _EtfSellNumber = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_3 _EtfSellVolume = null;
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"EtfSellVolume", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_3 EtfSellVolume
    {
      get { return _EtfSellVolume; }
      set { _EtfSellVolume = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_5 _ETFSellMoney = null;
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"ETFSellMoney", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_5 ETFSellMoney
    {
      get { return _ETFSellMoney; }
      set { _ETFSellMoney = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_4 _YieldToMatu = null;
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"YieldToMatu", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_4 YieldToMatu
    {
      get { return _YieldToMatu; }
      set { _YieldToMatu = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_3 _TotWarExNum = null;
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"TotWarExNum", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_3 TotWarExNum
    {
      get { return _TotWarExNum; }
      set { _TotWarExNum = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_3 _WarLowerPri = null;
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"WarLowerPri", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_3 WarLowerPri
    {
      get { return _WarLowerPri; }
      set { _WarLowerPri = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_3 _WarUpperPri = null;
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"WarUpperPri", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_3 WarUpperPri
    {
      get { return _WarUpperPri; }
      set { _WarUpperPri = value; }
    }
    private uint _WiDBuyNum = default(uint);
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"WiDBuyNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint WiDBuyNum
    {
      get { return _WiDBuyNum; }
      set { _WiDBuyNum = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_3 _WiDBuyVol = null;
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"WiDBuyVol", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_3 WiDBuyVol
    {
      get { return _WiDBuyVol; }
      set { _WiDBuyVol = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_5 _WiDBuyMon = null;
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"WiDBuyMon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_5 WiDBuyMon
    {
      get { return _WiDBuyMon; }
      set { _WiDBuyMon = value; }
    }
    private uint _WiDSellNum = default(uint);
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"WiDSellNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint WiDSellNum
    {
      get { return _WiDSellNum; }
      set { _WiDSellNum = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_3 _WiDSellVol = null;
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"WiDSellVol", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_3 WiDSellVol
    {
      get { return _WiDSellVol; }
      set { _WiDSellVol = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_5 _WiDSellMon = null;
    [global::ProtoBuf.ProtoMember(35, IsRequired = false, Name=@"WiDSellMon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_5 WiDSellMon
    {
      get { return _WiDSellMon; }
      set { _WiDSellMon = value; }
    }
    private uint _TotBidNum = default(uint);
    [global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"TotBidNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint TotBidNum
    {
      get { return _TotBidNum; }
      set { _TotBidNum = value; }
    }
    private uint _TotSellNum = default(uint);
    [global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"TotSellNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint TotSellNum
    {
      get { return _TotSellNum; }
      set { _TotSellNum = value; }
    }
    private uint _MaxBidDur = default(uint);
    [global::ProtoBuf.ProtoMember(38, IsRequired = false, Name=@"MaxBidDur", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint MaxBidDur
    {
      get { return _MaxBidDur; }
      set { _MaxBidDur = value; }
    }
    private uint _MaxSellDur = default(uint);
    [global::ProtoBuf.ProtoMember(39, IsRequired = false, Name=@"MaxSellDur", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint MaxSellDur
    {
      get { return _MaxSellDur; }
      set { _MaxSellDur = value; }
    }
    private uint _BidNum = default(uint);
    [global::ProtoBuf.ProtoMember(40, IsRequired = false, Name=@"BidNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint BidNum
    {
      get { return _BidNum; }
      set { _BidNum = value; }
    }
    private uint _SellNum = default(uint);
    [global::ProtoBuf.ProtoMember(41, IsRequired = false, Name=@"SellNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint SellNum
    {
      get { return _SellNum; }
      set { _SellNum = value; }
    }
    private readonly global::System.Collections.Generic.List<datayes.mdl.mdl_shl2_pbmsg.SHL2MarketData.BidLevelsItem> _BidLevels = new global::System.Collections.Generic.List<datayes.mdl.mdl_shl2_pbmsg.SHL2MarketData.BidLevelsItem>();
    [global::ProtoBuf.ProtoMember(42, Name=@"BidLevels", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<datayes.mdl.mdl_shl2_pbmsg.SHL2MarketData.BidLevelsItem> BidLevels
    {
      get { return _BidLevels; }
    }
  
    private readonly global::System.Collections.Generic.List<datayes.mdl.mdl_shl2_pbmsg.SHL2MarketData.SellLevelsItem> _SellLevels = new global::System.Collections.Generic.List<datayes.mdl.mdl_shl2_pbmsg.SHL2MarketData.SellLevelsItem>();
    [global::ProtoBuf.ProtoMember(51, Name=@"SellLevels", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<datayes.mdl.mdl_shl2_pbmsg.SHL2MarketData.SellLevelsItem> SellLevels
    {
      get { return _SellLevels; }
    }
  
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _IOPV = null;
    [global::ProtoBuf.ProtoMember(60, IsRequired = false, Name=@"IOPV", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 IOPV
    {
      get { return _IOPV; }
      set { _IOPV = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BidLevelsItem")]
  public partial class BidLevelsItem : global::ProtoBuf.IExtensible
  {
    public BidLevelsItem() {}
    
    private uint _PriLevOpera = default(uint);
    [global::ProtoBuf.ProtoMember(43, IsRequired = false, Name=@"PriLevOpera", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint PriLevOpera
    {
      get { return _PriLevOpera; }
      set { _PriLevOpera = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _OrderPrice = null;
    [global::ProtoBuf.ProtoMember(44, IsRequired = false, Name=@"OrderPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 OrderPrice
    {
      get { return _OrderPrice; }
      set { _OrderPrice = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_3 _OrderVol = null;
    [global::ProtoBuf.ProtoMember(45, IsRequired = false, Name=@"OrderVol", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_3 OrderVol
    {
      get { return _OrderVol; }
      set { _OrderVol = value; }
    }
    private uint _OrderNum = default(uint);
    [global::ProtoBuf.ProtoMember(46, IsRequired = false, Name=@"OrderNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint OrderNum
    {
      get { return _OrderNum; }
      set { _OrderNum = value; }
    }
    private readonly global::System.Collections.Generic.List<datayes.mdl.mdl_shl2_pbmsg.SHL2MarketData.BidLevelsItem.NOrdersItem> _NOrders = new global::System.Collections.Generic.List<datayes.mdl.mdl_shl2_pbmsg.SHL2MarketData.BidLevelsItem.NOrdersItem>();
    [global::ProtoBuf.ProtoMember(47, Name=@"NOrders", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<datayes.mdl.mdl_shl2_pbmsg.SHL2MarketData.BidLevelsItem.NOrdersItem> NOrders
    {
      get { return _NOrders; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NOrdersItem")]
  public partial class NOrdersItem : global::ProtoBuf.IExtensible
  {
    public NOrdersItem() {}
    
    private uint _OrderQueOper = default(uint);
    [global::ProtoBuf.ProtoMember(48, IsRequired = false, Name=@"OrderQueOper", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint OrderQueOper
    {
      get { return _OrderQueOper; }
      set { _OrderQueOper = value; }
    }
    private uint _OrderQueID = default(uint);
    [global::ProtoBuf.ProtoMember(49, IsRequired = false, Name=@"OrderQueID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint OrderQueID
    {
      get { return _OrderQueID; }
      set { _OrderQueID = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_3 _OrderQty = null;
    [global::ProtoBuf.ProtoMember(50, IsRequired = false, Name=@"OrderQty", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_3 OrderQty
    {
      get { return _OrderQty; }
      set { _OrderQty = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SellLevelsItem")]
  public partial class SellLevelsItem : global::ProtoBuf.IExtensible
  {
    public SellLevelsItem() {}
    
    private uint _PriLevOpera = default(uint);
    [global::ProtoBuf.ProtoMember(52, IsRequired = false, Name=@"PriLevOpera", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint PriLevOpera
    {
      get { return _PriLevOpera; }
      set { _PriLevOpera = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _OrderPrice = null;
    [global::ProtoBuf.ProtoMember(53, IsRequired = false, Name=@"OrderPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 OrderPrice
    {
      get { return _OrderPrice; }
      set { _OrderPrice = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_3 _OrderVol = null;
    [global::ProtoBuf.ProtoMember(54, IsRequired = false, Name=@"OrderVol", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_3 OrderVol
    {
      get { return _OrderVol; }
      set { _OrderVol = value; }
    }
    private uint _OrderNum = default(uint);
    [global::ProtoBuf.ProtoMember(55, IsRequired = false, Name=@"OrderNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint OrderNum
    {
      get { return _OrderNum; }
      set { _OrderNum = value; }
    }
    private readonly global::System.Collections.Generic.List<datayes.mdl.mdl_shl2_pbmsg.SHL2MarketData.SellLevelsItem.NoOrdersItem> _NoOrders = new global::System.Collections.Generic.List<datayes.mdl.mdl_shl2_pbmsg.SHL2MarketData.SellLevelsItem.NoOrdersItem>();
    [global::ProtoBuf.ProtoMember(56, Name=@"NoOrders", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<datayes.mdl.mdl_shl2_pbmsg.SHL2MarketData.SellLevelsItem.NoOrdersItem> NoOrders
    {
      get { return _NoOrders; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NoOrdersItem")]
  public partial class NoOrdersItem : global::ProtoBuf.IExtensible
  {
    public NoOrdersItem() {}
    
    private uint _OrderQueOper = default(uint);
    [global::ProtoBuf.ProtoMember(57, IsRequired = false, Name=@"OrderQueOper", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint OrderQueOper
    {
      get { return _OrderQueOper; }
      set { _OrderQueOper = value; }
    }
    private uint _OrderQueID = default(uint);
    [global::ProtoBuf.ProtoMember(58, IsRequired = false, Name=@"OrderQueID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint OrderQueID
    {
      get { return _OrderQueID; }
      set { _OrderQueID = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_3 _OrderQty = null;
    [global::ProtoBuf.ProtoMember(59, IsRequired = false, Name=@"OrderQty", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_3 OrderQty
    {
      get { return _OrderQty; }
      set { _OrderQty = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MID")]
    public enum MID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MessageID", Value=4)]
      MessageID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SID")]
    public enum SID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceID", Value=4)]
      ServiceID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"VID")]
    public enum VID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceVersion", Value=101)]
      ServiceVersion = 101
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SHL2VirtualAuctionPrice")]
  public partial class SHL2VirtualAuctionPrice : global::ProtoBuf.IExtensible
  {
    public SHL2VirtualAuctionPrice() {}
    
    private uint _UpdateTime = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"UpdateTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint UpdateTime
    {
      get { return _UpdateTime; }
      set { _UpdateTime = value; }
    }
    private uint _DataStatus = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"DataStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint DataStatus
    {
      get { return _DataStatus; }
      set { _DataStatus = value; }
    }
    private string _SecurityID = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"SecurityID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SecurityID
    {
      get { return _SecurityID; }
      set { _SecurityID = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _VirPri = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"VirPri", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 VirPri
    {
      get { return _VirPri; }
      set { _VirPri = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_3 _VirAucQty = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"VirAucQty", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_3 VirAucQty
    {
      get { return _VirAucQty; }
      set { _VirAucQty = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_3 _LeaQty = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"LeaQty", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_3 LeaQty
    {
      get { return _LeaQty; }
      set { _LeaQty = value; }
    }
    private string _Side = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"Side", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Side
    {
      get { return _Side; }
      set { _Side = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"MID")]
    public enum MID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MessageID", Value=5)]
      MessageID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SID")]
    public enum SID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceID", Value=4)]
      ServiceID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"VID")]
    public enum VID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceVersion", Value=101)]
      ServiceVersion = 101
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SHL2Index")]
  public partial class SHL2Index : global::ProtoBuf.IExtensible
  {
    public SHL2Index() {}
    
    private uint _UpdateTime = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"UpdateTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint UpdateTime
    {
      get { return _UpdateTime; }
      set { _UpdateTime = value; }
    }
    private uint _DataStatus = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"DataStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint DataStatus
    {
      get { return _DataStatus; }
      set { _DataStatus = value; }
    }
    private string _SecurityID = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"SecurityID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SecurityID
    {
      get { return _SecurityID; }
      set { _SecurityID = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_5 _PreCloseIndex = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"PreCloseIndex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_5 PreCloseIndex
    {
      get { return _PreCloseIndex; }
      set { _PreCloseIndex = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_5 _OpenIndex = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"OpenIndex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_5 OpenIndex
    {
      get { return _OpenIndex; }
      set { _OpenIndex = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_1 _Turnover = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Turnover", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_1 Turnover
    {
      get { return _Turnover; }
      set { _Turnover = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_5 _HighIndex = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"HighIndex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_5 HighIndex
    {
      get { return _HighIndex; }
      set { _HighIndex = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_5 _LowIndex = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"LowIndex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_5 LowIndex
    {
      get { return _LowIndex; }
      set { _LowIndex = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_5 _LastIndex = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"LastIndex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_5 LastIndex
    {
      get { return _LastIndex; }
      set { _LastIndex = value; }
    }
    private uint _TradTime = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"TradTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint TradTime
    {
      get { return _TradTime; }
      set { _TradTime = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_5 _TradVolume = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"TradVolume", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_5 TradVolume
    {
      get { return _TradVolume; }
      set { _TradVolume = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_5 _CloseIndex = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"CloseIndex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_5 CloseIndex
    {
      get { return _CloseIndex; }
      set { _CloseIndex = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"MID")]
    public enum MID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MessageID", Value=6)]
      MessageID = 6
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SID")]
    public enum SID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceID", Value=4)]
      ServiceID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"VID")]
    public enum VID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceVersion", Value=101)]
      ServiceVersion = 101
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SHL2MarketOverview")]
  public partial class SHL2MarketOverview : global::ProtoBuf.IExtensible
  {
    public SHL2MarketOverview() {}
    
    private uint _UpdateTime = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"UpdateTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint UpdateTime
    {
      get { return _UpdateTime; }
      set { _UpdateTime = value; }
    }
    private uint _DataStatus = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"DataStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint DataStatus
    {
      get { return _DataStatus; }
      set { _DataStatus = value; }
    }
    private string _SecurityID = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"SecurityID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SecurityID
    {
      get { return _SecurityID; }
      set { _SecurityID = value; }
    }
    private uint _UpdateMill = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"UpdateMill", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint UpdateMill
    {
      get { return _UpdateMill; }
      set { _UpdateMill = value; }
    }
    private uint _TradDay = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"TradDay", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint TradDay
    {
      get { return _TradDay; }
      set { _TradDay = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"MID")]
    public enum MID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MessageID", Value=7)]
      MessageID = 7
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SID")]
    public enum SID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceID", Value=4)]
      ServiceID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"VID")]
    public enum VID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceVersion", Value=101)]
      ServiceVersion = 101
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SHL2Statics")]
  public partial class SHL2Statics : global::ProtoBuf.IExtensible
  {
    public SHL2Statics() {}
    
    private string _SecurityID = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"SecurityID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SecurityID
    {
      get { return _SecurityID; }
      set { _SecurityID = value; }
    }
    private uint _UpdateTime = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"UpdateTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint UpdateTime
    {
      get { return _UpdateTime; }
      set { _UpdateTime = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _OpenPrice = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"OpenPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 OpenPrice
    {
      get { return _OpenPrice; }
      set { _OpenPrice = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _HighPrice = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"HighPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 HighPrice
    {
      get { return _HighPrice; }
      set { _HighPrice = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _LowPrice = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"LowPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 LowPrice
    {
      get { return _LowPrice; }
      set { _LowPrice = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.float_3 _ClosePrice = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"ClosePrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.float_3 ClosePrice
    {
      get { return _ClosePrice; }
      set { _ClosePrice = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_3 _TradVolume = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"TradVolume", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_3 TradVolume
    {
      get { return _TradVolume; }
      set { _TradVolume = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_5 _Turnover = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"Turnover", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_5 Turnover
    {
      get { return _Turnover; }
      set { _Turnover = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"MID")]
    public enum MID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MessageID", Value=8)]
      MessageID = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SID")]
    public enum SID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceID", Value=4)]
      ServiceID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"VID")]
    public enum VID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceVersion", Value=101)]
      ServiceVersion = 101
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OPTLevel1")]
  public partial class OPTLevel1 : global::ProtoBuf.IExtensible
  {
    public OPTLevel1() {}
    
    private uint _UpdateTime = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"UpdateTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint UpdateTime
    {
      get { return _UpdateTime; }
      set { _UpdateTime = value; }
    }
    private int _DataStatus = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"DataStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int DataStatus
    {
      get { return _DataStatus; }
      set { _DataStatus = value; }
    }
    private string _SecurityID = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"SecurityID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SecurityID
    {
      get { return _SecurityID; }
      set { _SecurityID = value; }
    }
    private int _ImageStatus = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ImageStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ImageStatus
    {
      get { return _ImageStatus; }
      set { _ImageStatus = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_4 _PreSettlPrice = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"PreSettlPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_4 PreSettlPrice
    {
      get { return _PreSettlPrice; }
      set { _PreSettlPrice = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_4 _SettlPrice = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"SettlPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_4 SettlPrice
    {
      get { return _SettlPrice; }
      set { _SettlPrice = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_4 _OpenPx = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"OpenPx", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_4 OpenPx
    {
      get { return _OpenPx; }
      set { _OpenPx = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_4 _HighPx = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"HighPx", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_4 HighPx
    {
      get { return _HighPx; }
      set { _HighPx = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_4 _LowPx = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"LowPx", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_4 LowPx
    {
      get { return _LowPx; }
      set { _LowPx = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_4 _LastPx = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"LastPx", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_4 LastPx
    {
      get { return _LastPx; }
      set { _LastPx = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_4 _ClosePx = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"ClosePx", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_4 ClosePx
    {
      get { return _ClosePx; }
      set { _ClosePx = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_4 _AuctionPrice = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"AuctionPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_4 AuctionPrice
    {
      get { return _AuctionPrice; }
      set { _AuctionPrice = value; }
    }
    private long _AuctionQty = default(long);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"AuctionQty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long AuctionQty
    {
      get { return _AuctionQty; }
      set { _AuctionQty = value; }
    }
    private long _TotalLongPosition = default(long);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"TotalLongPosition", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long TotalLongPosition
    {
      get { return _TotalLongPosition; }
      set { _TotalLongPosition = value; }
    }
    private readonly global::System.Collections.Generic.List<datayes.mdl.mdl_shl2_pbmsg.OPTLevel1.BidPriceLevelItem> _BidPriceLevel = new global::System.Collections.Generic.List<datayes.mdl.mdl_shl2_pbmsg.OPTLevel1.BidPriceLevelItem>();
    [global::ProtoBuf.ProtoMember(15, Name=@"BidPriceLevel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<datayes.mdl.mdl_shl2_pbmsg.OPTLevel1.BidPriceLevelItem> BidPriceLevel
    {
      get { return _BidPriceLevel; }
    }
  
    private readonly global::System.Collections.Generic.List<datayes.mdl.mdl_shl2_pbmsg.OPTLevel1.OfferPriceLevelItem> _OfferPriceLevel = new global::System.Collections.Generic.List<datayes.mdl.mdl_shl2_pbmsg.OPTLevel1.OfferPriceLevelItem>();
    [global::ProtoBuf.ProtoMember(18, Name=@"OfferPriceLevel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<datayes.mdl.mdl_shl2_pbmsg.OPTLevel1.OfferPriceLevelItem> OfferPriceLevel
    {
      get { return _OfferPriceLevel; }
    }
  
    private long _TotalVolumeTrade = default(long);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"TotalVolumeTrade", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long TotalVolumeTrade
    {
      get { return _TotalVolumeTrade; }
      set { _TotalVolumeTrade = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_2 _TotalValueTrade = null;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"TotalValueTrade", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_2 TotalValueTrade
    {
      get { return _TotalValueTrade; }
      set { _TotalValueTrade = value; }
    }
    private string _TradingPhaseCode = "";
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"TradingPhaseCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string TradingPhaseCode
    {
      get { return _TradingPhaseCode; }
      set { _TradingPhaseCode = value; }
    }
    private uint _OrigTime = default(uint);
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"OrigTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint OrigTime
    {
      get { return _OrigTime; }
      set { _OrigTime = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BidPriceLevelItem")]
  public partial class BidPriceLevelItem : global::ProtoBuf.IExtensible
  {
    public BidPriceLevelItem() {}
    
    private long _BidSize = default(long);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"BidSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long BidSize
    {
      get { return _BidSize; }
      set { _BidSize = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_4 _BidPx = null;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"BidPx", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_4 BidPx
    {
      get { return _BidPx; }
      set { _BidPx = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OfferPriceLevelItem")]
  public partial class OfferPriceLevelItem : global::ProtoBuf.IExtensible
  {
    public OfferPriceLevelItem() {}
    
    private long _OfferSize = default(long);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"OfferSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long OfferSize
    {
      get { return _OfferSize; }
      set { _OfferSize = value; }
    }
    private datayes.mdl.mdl_shl2_pbmsg.double_4 _OfferPx = null;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"OfferPx", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl2_pbmsg.double_4 OfferPx
    {
      get { return _OfferPx; }
      set { _OfferPx = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MID")]
    public enum MID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MessageID", Value=9)]
      MessageID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SID")]
    public enum SID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceID", Value=4)]
      ServiceID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"VID")]
    public enum VID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceVersion", Value=101)]
      ServiceVersion = 101
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MDLSHL2ServiceVersion")]
    public enum MDLSHL2ServiceVersion
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MDLVID_MDL_SHL2", Value=101)]
      MDLVID_MDL_SHL2 = 101
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MDLSHL2MessageID")]
    public enum MDLSHL2MessageID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MDLMID_MDL_SHL2_SHL1Stock", Value=2)]
      MDLMID_MDL_SHL2_SHL1Stock = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MDLMID_MDL_SHL2_SHL2Transaction", Value=3)]
      MDLMID_MDL_SHL2_SHL2Transaction = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MDLMID_MDL_SHL2_SHL2MarketData", Value=4)]
      MDLMID_MDL_SHL2_SHL2MarketData = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MDLMID_MDL_SHL2_SHL2VirtualAuctionPrice", Value=5)]
      MDLMID_MDL_SHL2_SHL2VirtualAuctionPrice = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MDLMID_MDL_SHL2_SHL2Index", Value=6)]
      MDLMID_MDL_SHL2_SHL2Index = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MDLMID_MDL_SHL2_SHL2MarketOverview", Value=7)]
      MDLMID_MDL_SHL2_SHL2MarketOverview = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MDLMID_MDL_SHL2_SHL2Statics", Value=8)]
      MDLMID_MDL_SHL2_SHL2Statics = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MDLMID_MDL_SHL2_OPTLevel1", Value=9)]
      MDLMID_MDL_SHL2_OPTLevel1 = 9
    }
  
}