//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input/mdl_shl1_msg.proto
namespace datayes.mdl.mdl_shl1_pbmsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"double_3")]
  public partial class double_3 : global::ProtoBuf.IExtensible
  {
    public double_3() {}
    
    private long _Value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long Value
    {
      get { return _Value; }
      set { _Value = value; }
    }
    private uint _DecimalShift = (uint)1000;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"DecimalShift", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)1000)]
    public uint DecimalShift
    {
      get { return _DecimalShift; }
      set { _DecimalShift = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"float_3")]
  public partial class float_3 : global::ProtoBuf.IExtensible
  {
    public float_3() {}
    
    private int _Value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Value
    {
      get { return _Value; }
      set { _Value = value; }
    }
    private uint _DecimalShift = (uint)1000;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"DecimalShift", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)1000)]
    public uint DecimalShift
    {
      get { return _DecimalShift; }
      set { _DecimalShift = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"double_4")]
  public partial class double_4 : global::ProtoBuf.IExtensible
  {
    public double_4() {}
    
    private long _Value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long Value
    {
      get { return _Value; }
      set { _Value = value; }
    }
    private uint _DecimalShift = (uint)10000;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"DecimalShift", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)10000)]
    public uint DecimalShift
    {
      get { return _DecimalShift; }
      set { _DecimalShift = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"double_2")]
  public partial class double_2 : global::ProtoBuf.IExtensible
  {
    public double_2() {}
    
    private long _Value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long Value
    {
      get { return _Value; }
      set { _Value = value; }
    }
    private uint _DecimalShift = (uint)100;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"DecimalShift", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)100)]
    public uint DecimalShift
    {
      get { return _DecimalShift; }
      set { _DecimalShift = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Indexes")]
  public partial class Indexes : global::ProtoBuf.IExtensible
  {
    public Indexes() {}
    
    private string _IndexID = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"IndexID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string IndexID
    {
      get { return _IndexID; }
      set { _IndexID = value; }
    }
    private string _IndexName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"IndexName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string IndexName
    {
      get { return _IndexName; }
      set { _IndexName = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_4 _PreCloseIndex = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"PreCloseIndex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_4 PreCloseIndex
    {
      get { return _PreCloseIndex; }
      set { _PreCloseIndex = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_4 _OpenIndex = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"OpenIndex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_4 OpenIndex
    {
      get { return _OpenIndex; }
      set { _OpenIndex = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_2 _Turnover = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Turnover", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_2 Turnover
    {
      get { return _Turnover; }
      set { _Turnover = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_4 _HighIndex = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"HighIndex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_4 HighIndex
    {
      get { return _HighIndex; }
      set { _HighIndex = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_4 _LowIndex = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"LowIndex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_4 LowIndex
    {
      get { return _LowIndex; }
      set { _LowIndex = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_4 _LastIndex = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"LastIndex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_4 LastIndex
    {
      get { return _LastIndex; }
      set { _LastIndex = value; }
    }
    private ulong _TradVolume = default(ulong);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"TradVolume", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong TradVolume
    {
      get { return _TradVolume; }
      set { _TradVolume = value; }
    }
    private uint _UpdateTime = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"UpdateTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint UpdateTime
    {
      get { return _UpdateTime; }
      set { _UpdateTime = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_4 _CloseIndex = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"CloseIndex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_4 CloseIndex
    {
      get { return _CloseIndex; }
      set { _CloseIndex = value; }
    }
    private string _TradingPhaseCode = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"TradingPhaseCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string TradingPhaseCode
    {
      get { return _TradingPhaseCode; }
      set { _TradingPhaseCode = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"MID")]
    public enum MID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MessageID", Value=3)]
      MessageID = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SID")]
    public enum SID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceID", Value=3)]
      ServiceID = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"VID")]
    public enum VID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceVersion", Value=101)]
      ServiceVersion = 101
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Equity")]
  public partial class Equity : global::ProtoBuf.IExtensible
  {
    public Equity() {}
    
    private string _SecurityID = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"SecurityID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SecurityID
    {
      get { return _SecurityID; }
      set { _SecurityID = value; }
    }
    private string _SecurityName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SecurityName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SecurityName
    {
      get { return _SecurityName; }
      set { _SecurityName = value; }
    }
    private string _TradingPhaseCode = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"TradingPhaseCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string TradingPhaseCode
    {
      get { return _TradingPhaseCode; }
      set { _TradingPhaseCode = value; }
    }
    private uint _UpdateTime = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"UpdateTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint UpdateTime
    {
      get { return _UpdateTime; }
      set { _UpdateTime = value; }
    }
    private ulong _Volume = default(ulong);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Volume", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Volume
    {
      get { return _Volume; }
      set { _Volume = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_2 _Turnover = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Turnover", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_2 Turnover
    {
      get { return _Turnover; }
      set { _Turnover = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_3 _PreCloPrice = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"PreCloPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_3 PreCloPrice
    {
      get { return _PreCloPrice; }
      set { _PreCloPrice = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_3 _OpenPrice = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"OpenPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_3 OpenPrice
    {
      get { return _OpenPrice; }
      set { _OpenPrice = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_3 _HighPrice = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"HighPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_3 HighPrice
    {
      get { return _HighPrice; }
      set { _HighPrice = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_3 _LowPrice = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"LowPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_3 LowPrice
    {
      get { return _LowPrice; }
      set { _LowPrice = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_3 _LastPrice = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"LastPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_3 LastPrice
    {
      get { return _LastPrice; }
      set { _LastPrice = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_3 _ClosePrice = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"ClosePrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_3 ClosePrice
    {
      get { return _ClosePrice; }
      set { _ClosePrice = value; }
    }
    private readonly global::System.Collections.Generic.List<datayes.mdl.mdl_shl1_pbmsg.Equity.BidPriceLevelItem> _BidPriceLevel = new global::System.Collections.Generic.List<datayes.mdl.mdl_shl1_pbmsg.Equity.BidPriceLevelItem>();
    [global::ProtoBuf.ProtoMember(13, Name=@"BidPriceLevel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<datayes.mdl.mdl_shl1_pbmsg.Equity.BidPriceLevelItem> BidPriceLevel
    {
      get { return _BidPriceLevel; }
    }
  
    private readonly global::System.Collections.Generic.List<datayes.mdl.mdl_shl1_pbmsg.Equity.AskPriceLevelItem> _AskPriceLevel = new global::System.Collections.Generic.List<datayes.mdl.mdl_shl1_pbmsg.Equity.AskPriceLevelItem>();
    [global::ProtoBuf.ProtoMember(16, Name=@"AskPriceLevel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<datayes.mdl.mdl_shl1_pbmsg.Equity.AskPriceLevelItem> AskPriceLevel
    {
      get { return _AskPriceLevel; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BidPriceLevelItem")]
  public partial class BidPriceLevelItem : global::ProtoBuf.IExtensible
  {
    public BidPriceLevelItem() {}
    
    private ulong _Volume = default(ulong);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"Volume", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Volume
    {
      get { return _Volume; }
      set { _Volume = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_3 _Price = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"Price", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_3 Price
    {
      get { return _Price; }
      set { _Price = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AskPriceLevelItem")]
  public partial class AskPriceLevelItem : global::ProtoBuf.IExtensible
  {
    public AskPriceLevelItem() {}
    
    private ulong _Volume = default(ulong);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"Volume", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Volume
    {
      get { return _Volume; }
      set { _Volume = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_3 _Price = null;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"Price", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_3 Price
    {
      get { return _Price; }
      set { _Price = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MID")]
    public enum MID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MessageID", Value=4)]
      MessageID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SID")]
    public enum SID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceID", Value=3)]
      ServiceID = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"VID")]
    public enum VID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceVersion", Value=101)]
      ServiceVersion = 101
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Bonds")]
  public partial class Bonds : global::ProtoBuf.IExtensible
  {
    public Bonds() {}
    
    private string _SecurityID = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"SecurityID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SecurityID
    {
      get { return _SecurityID; }
      set { _SecurityID = value; }
    }
    private string _SecurityName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SecurityName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SecurityName
    {
      get { return _SecurityName; }
      set { _SecurityName = value; }
    }
    private string _TradingPhaseCode = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"TradingPhaseCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string TradingPhaseCode
    {
      get { return _TradingPhaseCode; }
      set { _TradingPhaseCode = value; }
    }
    private uint _UpdateTime = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"UpdateTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint UpdateTime
    {
      get { return _UpdateTime; }
      set { _UpdateTime = value; }
    }
    private ulong _Volume = default(ulong);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Volume", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Volume
    {
      get { return _Volume; }
      set { _Volume = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_2 _Turnover = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Turnover", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_2 Turnover
    {
      get { return _Turnover; }
      set { _Turnover = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_3 _PreCloPrice = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"PreCloPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_3 PreCloPrice
    {
      get { return _PreCloPrice; }
      set { _PreCloPrice = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_3 _OpenPrice = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"OpenPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_3 OpenPrice
    {
      get { return _OpenPrice; }
      set { _OpenPrice = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_3 _HighPrice = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"HighPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_3 HighPrice
    {
      get { return _HighPrice; }
      set { _HighPrice = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_3 _LowPrice = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"LowPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_3 LowPrice
    {
      get { return _LowPrice; }
      set { _LowPrice = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_3 _LastPrice = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"LastPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_3 LastPrice
    {
      get { return _LastPrice; }
      set { _LastPrice = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_3 _ClosePrice = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"ClosePrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_3 ClosePrice
    {
      get { return _ClosePrice; }
      set { _ClosePrice = value; }
    }
    private readonly global::System.Collections.Generic.List<datayes.mdl.mdl_shl1_pbmsg.Bonds.BidPriceLevelItem> _BidPriceLevel = new global::System.Collections.Generic.List<datayes.mdl.mdl_shl1_pbmsg.Bonds.BidPriceLevelItem>();
    [global::ProtoBuf.ProtoMember(13, Name=@"BidPriceLevel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<datayes.mdl.mdl_shl1_pbmsg.Bonds.BidPriceLevelItem> BidPriceLevel
    {
      get { return _BidPriceLevel; }
    }
  
    private readonly global::System.Collections.Generic.List<datayes.mdl.mdl_shl1_pbmsg.Bonds.AskPriceLevelItem> _AskPriceLevel = new global::System.Collections.Generic.List<datayes.mdl.mdl_shl1_pbmsg.Bonds.AskPriceLevelItem>();
    [global::ProtoBuf.ProtoMember(16, Name=@"AskPriceLevel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<datayes.mdl.mdl_shl1_pbmsg.Bonds.AskPriceLevelItem> AskPriceLevel
    {
      get { return _AskPriceLevel; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BidPriceLevelItem")]
  public partial class BidPriceLevelItem : global::ProtoBuf.IExtensible
  {
    public BidPriceLevelItem() {}
    
    private ulong _Volume = default(ulong);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"Volume", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Volume
    {
      get { return _Volume; }
      set { _Volume = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_3 _Price = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"Price", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_3 Price
    {
      get { return _Price; }
      set { _Price = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AskPriceLevelItem")]
  public partial class AskPriceLevelItem : global::ProtoBuf.IExtensible
  {
    public AskPriceLevelItem() {}
    
    private ulong _Volume = default(ulong);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"Volume", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Volume
    {
      get { return _Volume; }
      set { _Volume = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_3 _Price = null;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"Price", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_3 Price
    {
      get { return _Price; }
      set { _Price = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MID")]
    public enum MID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MessageID", Value=5)]
      MessageID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SID")]
    public enum SID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceID", Value=3)]
      ServiceID = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"VID")]
    public enum VID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceVersion", Value=101)]
      ServiceVersion = 101
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Funds")]
  public partial class Funds : global::ProtoBuf.IExtensible
  {
    public Funds() {}
    
    private string _SecurityID = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"SecurityID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SecurityID
    {
      get { return _SecurityID; }
      set { _SecurityID = value; }
    }
    private string _SecurityName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SecurityName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SecurityName
    {
      get { return _SecurityName; }
      set { _SecurityName = value; }
    }
    private string _TradingPhaseCode = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"TradingPhaseCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string TradingPhaseCode
    {
      get { return _TradingPhaseCode; }
      set { _TradingPhaseCode = value; }
    }
    private uint _UpdateTime = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"UpdateTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint UpdateTime
    {
      get { return _UpdateTime; }
      set { _UpdateTime = value; }
    }
    private ulong _Volume = default(ulong);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Volume", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Volume
    {
      get { return _Volume; }
      set { _Volume = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_2 _Turnover = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Turnover", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_2 Turnover
    {
      get { return _Turnover; }
      set { _Turnover = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_3 _PreCloPrice = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"PreCloPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_3 PreCloPrice
    {
      get { return _PreCloPrice; }
      set { _PreCloPrice = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_3 _OpenPrice = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"OpenPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_3 OpenPrice
    {
      get { return _OpenPrice; }
      set { _OpenPrice = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_3 _HighPrice = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"HighPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_3 HighPrice
    {
      get { return _HighPrice; }
      set { _HighPrice = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_3 _LowPrice = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"LowPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_3 LowPrice
    {
      get { return _LowPrice; }
      set { _LowPrice = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_3 _LastPrice = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"LastPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_3 LastPrice
    {
      get { return _LastPrice; }
      set { _LastPrice = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_3 _ClosePrice = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"ClosePrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_3 ClosePrice
    {
      get { return _ClosePrice; }
      set { _ClosePrice = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_3 _IOPV = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"IOPV", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_3 IOPV
    {
      get { return _IOPV; }
      set { _IOPV = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_3 _PreCloseIOPV = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"PreCloseIOPV", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_3 PreCloseIOPV
    {
      get { return _PreCloseIOPV; }
      set { _PreCloseIOPV = value; }
    }
    private readonly global::System.Collections.Generic.List<datayes.mdl.mdl_shl1_pbmsg.Funds.BidPriceLevelItem> _BidPriceLevel = new global::System.Collections.Generic.List<datayes.mdl.mdl_shl1_pbmsg.Funds.BidPriceLevelItem>();
    [global::ProtoBuf.ProtoMember(15, Name=@"BidPriceLevel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<datayes.mdl.mdl_shl1_pbmsg.Funds.BidPriceLevelItem> BidPriceLevel
    {
      get { return _BidPriceLevel; }
    }
  
    private readonly global::System.Collections.Generic.List<datayes.mdl.mdl_shl1_pbmsg.Funds.AskPriceLevelItem> _AskPriceLevel = new global::System.Collections.Generic.List<datayes.mdl.mdl_shl1_pbmsg.Funds.AskPriceLevelItem>();
    [global::ProtoBuf.ProtoMember(18, Name=@"AskPriceLevel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<datayes.mdl.mdl_shl1_pbmsg.Funds.AskPriceLevelItem> AskPriceLevel
    {
      get { return _AskPriceLevel; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BidPriceLevelItem")]
  public partial class BidPriceLevelItem : global::ProtoBuf.IExtensible
  {
    public BidPriceLevelItem() {}
    
    private ulong _Volume = default(ulong);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"Volume", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Volume
    {
      get { return _Volume; }
      set { _Volume = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_3 _Price = null;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"Price", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_3 Price
    {
      get { return _Price; }
      set { _Price = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AskPriceLevelItem")]
  public partial class AskPriceLevelItem : global::ProtoBuf.IExtensible
  {
    public AskPriceLevelItem() {}
    
    private ulong _Volume = default(ulong);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"Volume", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Volume
    {
      get { return _Volume; }
      set { _Volume = value; }
    }
    private datayes.mdl.mdl_shl1_pbmsg.double_3 _Price = null;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"Price", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_shl1_pbmsg.double_3 Price
    {
      get { return _Price; }
      set { _Price = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MID")]
    public enum MID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MessageID", Value=6)]
      MessageID = 6
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SID")]
    public enum SID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceID", Value=3)]
      ServiceID = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"VID")]
    public enum VID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceVersion", Value=101)]
      ServiceVersion = 101
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MDLSHL1ServiceVersion")]
    public enum MDLSHL1ServiceVersion
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MDLVID_MDL_SHL1", Value=101)]
      MDLVID_MDL_SHL1 = 101
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MDLSHL1MessageID")]
    public enum MDLSHL1MessageID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MDLMID_MDL_SHL1_Indexes", Value=3)]
      MDLMID_MDL_SHL1_Indexes = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MDLMID_MDL_SHL1_Equity", Value=4)]
      MDLMID_MDL_SHL1_Equity = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MDLMID_MDL_SHL1_Bonds", Value=5)]
      MDLMID_MDL_SHL1_Bonds = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MDLMID_MDL_SHL1_Funds", Value=6)]
      MDLMID_MDL_SHL1_Funds = 6
    }
  
}