//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input/mdl_hkex_msg.proto
namespace datayes.mdl.mdl_hkex_pbmsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"float_3")]
  public partial class float_3 : global::ProtoBuf.IExtensible
  {
    public float_3() {}
    
    private int _Value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Value
    {
      get { return _Value; }
      set { _Value = value; }
    }
    private uint _DecimalShift = (uint)1000;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"DecimalShift", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)1000)]
    public uint DecimalShift
    {
      get { return _DecimalShift; }
      set { _DecimalShift = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"float_5")]
  public partial class float_5 : global::ProtoBuf.IExtensible
  {
    public float_5() {}
    
    private int _Value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Value
    {
      get { return _Value; }
      set { _Value = value; }
    }
    private uint _DecimalShift = (uint)100000;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"DecimalShift", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)100000)]
    public uint DecimalShift
    {
      get { return _DecimalShift; }
      set { _DecimalShift = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"double_3")]
  public partial class double_3 : global::ProtoBuf.IExtensible
  {
    public double_3() {}
    
    private long _Value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long Value
    {
      get { return _Value; }
      set { _Value = value; }
    }
    private uint _DecimalShift = (uint)1000;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"DecimalShift", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)1000)]
    public uint DecimalShift
    {
      get { return _DecimalShift; }
      set { _DecimalShift = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"double_2")]
  public partial class double_2 : global::ProtoBuf.IExtensible
  {
    public double_2() {}
    
    private long _Value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long Value
    {
      get { return _Value; }
      set { _Value = value; }
    }
    private uint _DecimalShift = (uint)100;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"DecimalShift", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)100)]
    public uint DecimalShift
    {
      get { return _DecimalShift; }
      set { _DecimalShift = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OMDMarketData")]
  public partial class OMDMarketData : global::ProtoBuf.IExtensible
  {
    public OMDMarketData() {}
    
    private string _TickerSymbol = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"TickerSymbol", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string TickerSymbol
    {
      get { return _TickerSymbol; }
      set { _TickerSymbol = value; }
    }
    private uint _TradTime = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"TradTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint TradTime
    {
      get { return _TradTime; }
      set { _TradTime = value; }
    }
    private int _TradStatus = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"TradStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int TradStatus
    {
      get { return _TradStatus; }
      set { _TradStatus = value; }
    }
    private int _TradType = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"TradType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int TradType
    {
      get { return _TradType; }
      set { _TradType = value; }
    }
    private datayes.mdl.mdl_hkex_pbmsg.float_3 _PreClosePrice = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"PreClosePrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_hkex_pbmsg.float_3 PreClosePrice
    {
      get { return _PreClosePrice; }
      set { _PreClosePrice = value; }
    }
    private datayes.mdl.mdl_hkex_pbmsg.float_3 _OpenPrice = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"OpenPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_hkex_pbmsg.float_3 OpenPrice
    {
      get { return _OpenPrice; }
      set { _OpenPrice = value; }
    }
    private datayes.mdl.mdl_hkex_pbmsg.float_3 _HighPrice = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"HighPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_hkex_pbmsg.float_3 HighPrice
    {
      get { return _HighPrice; }
      set { _HighPrice = value; }
    }
    private datayes.mdl.mdl_hkex_pbmsg.float_3 _LowPrice = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"LowPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_hkex_pbmsg.float_3 LowPrice
    {
      get { return _LowPrice; }
      set { _LowPrice = value; }
    }
    private datayes.mdl.mdl_hkex_pbmsg.float_3 _LastPrice = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"LastPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_hkex_pbmsg.float_3 LastPrice
    {
      get { return _LastPrice; }
      set { _LastPrice = value; }
    }
    private datayes.mdl.mdl_hkex_pbmsg.float_3 _NominalPrice = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"NominalPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_hkex_pbmsg.float_3 NominalPrice
    {
      get { return _NominalPrice; }
      set { _NominalPrice = value; }
    }
    private datayes.mdl.mdl_hkex_pbmsg.float_3 _VWAP = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"VWAP", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_hkex_pbmsg.float_3 VWAP
    {
      get { return _VWAP; }
      set { _VWAP = value; }
    }
    private datayes.mdl.mdl_hkex_pbmsg.float_3 _Change = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"Change", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_hkex_pbmsg.float_3 Change
    {
      get { return _Change; }
      set { _Change = value; }
    }
    private datayes.mdl.mdl_hkex_pbmsg.float_5 _ChangePct = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"ChangePct", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_hkex_pbmsg.float_5 ChangePct
    {
      get { return _ChangePct; }
      set { _ChangePct = value; }
    }
    private ulong _Quantity = default(ulong);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"Quantity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Quantity
    {
      get { return _Quantity; }
      set { _Quantity = value; }
    }
    private datayes.mdl.mdl_hkex_pbmsg.double_3 _Turnover = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"Turnover", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_hkex_pbmsg.double_3 Turnover
    {
      get { return _Turnover; }
      set { _Turnover = value; }
    }
    private uint _NumTrade = default(uint);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"NumTrade", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint NumTrade
    {
      get { return _NumTrade; }
      set { _NumTrade = value; }
    }
    private string _CurrencyCode = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"CurrencyCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string CurrencyCode
    {
      get { return _CurrencyCode; }
      set { _CurrencyCode = value; }
    }
    private datayes.mdl.mdl_hkex_pbmsg.float_3 _Yield = null;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"Yield", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_hkex_pbmsg.float_3 Yield
    {
      get { return _Yield; }
      set { _Yield = value; }
    }
    private datayes.mdl.mdl_hkex_pbmsg.float_3 _IEP = null;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"IEP", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_hkex_pbmsg.float_3 IEP
    {
      get { return _IEP; }
      set { _IEP = value; }
    }
    private ulong _AggQty = default(ulong);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"AggQty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong AggQty
    {
      get { return _AggQty; }
      set { _AggQty = value; }
    }
    private uint _TradSessionID = default(uint);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"TradSessionID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint TradSessionID
    {
      get { return _TradSessionID; }
      set { _TradSessionID = value; }
    }
    private uint _TradSessionSubID = default(uint);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"TradSessionSubID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint TradSessionSubID
    {
      get { return _TradSessionSubID; }
      set { _TradSessionSubID = value; }
    }
    private uint _TradSessionStatus = default(uint);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"TradSessionStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint TradSessionStatus
    {
      get { return _TradSessionStatus; }
      set { _TradSessionStatus = value; }
    }
    private readonly global::System.Collections.Generic.List<datayes.mdl.mdl_hkex_pbmsg.OMDMarketData.BidBookItem> _BidBook = new global::System.Collections.Generic.List<datayes.mdl.mdl_hkex_pbmsg.OMDMarketData.BidBookItem>();
    [global::ProtoBuf.ProtoMember(24, Name=@"BidBook", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<datayes.mdl.mdl_hkex_pbmsg.OMDMarketData.BidBookItem> BidBook
    {
      get { return _BidBook; }
    }
  
    private readonly global::System.Collections.Generic.List<datayes.mdl.mdl_hkex_pbmsg.OMDMarketData.AskBookItem> _AskBook = new global::System.Collections.Generic.List<datayes.mdl.mdl_hkex_pbmsg.OMDMarketData.AskBookItem>();
    [global::ProtoBuf.ProtoMember(27, Name=@"AskBook", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<datayes.mdl.mdl_hkex_pbmsg.OMDMarketData.AskBookItem> AskBook
    {
      get { return _AskBook; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BidBookItem")]
  public partial class BidBookItem : global::ProtoBuf.IExtensible
  {
    public BidBookItem() {}
    
    private ulong _Volume = default(ulong);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"Volume", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Volume
    {
      get { return _Volume; }
      set { _Volume = value; }
    }
    private datayes.mdl.mdl_hkex_pbmsg.float_3 _Price = null;
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"Price", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_hkex_pbmsg.float_3 Price
    {
      get { return _Price; }
      set { _Price = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AskBookItem")]
  public partial class AskBookItem : global::ProtoBuf.IExtensible
  {
    public AskBookItem() {}
    
    private ulong _Volume = default(ulong);
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"Volume", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Volume
    {
      get { return _Volume; }
      set { _Volume = value; }
    }
    private datayes.mdl.mdl_hkex_pbmsg.float_3 _Price = null;
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"Price", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_hkex_pbmsg.float_3 Price
    {
      get { return _Price; }
      set { _Price = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MID")]
    public enum MID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MessageID", Value=2)]
      MessageID = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SID")]
    public enum SID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceID", Value=11)]
      ServiceID = 11
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"VID")]
    public enum VID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceVersion", Value=101)]
      ServiceVersion = 101
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HangSengIndex")]
  public partial class HangSengIndex : global::ProtoBuf.IExtensible
  {
    public HangSengIndex() {}
    
    private uint _IndexType = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"IndexType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint IndexType
    {
      get { return _IndexType; }
      set { _IndexType = value; }
    }
    private uint _SecNo = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SecNo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint SecNo
    {
      get { return _SecNo; }
      set { _SecNo = value; }
    }
    private uint _Status = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Status
    {
      get { return _Status; }
      set { _Status = value; }
    }
    private datayes.mdl.mdl_hkex_pbmsg.double_2 _CurrentIndex = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"CurrentIndex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_hkex_pbmsg.double_2 CurrentIndex
    {
      get { return _CurrentIndex; }
      set { _CurrentIndex = value; }
    }
    private datayes.mdl.mdl_hkex_pbmsg.double_2 _DailyIndexHigh = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"DailyIndexHigh", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_hkex_pbmsg.double_2 DailyIndexHigh
    {
      get { return _DailyIndexHigh; }
      set { _DailyIndexHigh = value; }
    }
    private datayes.mdl.mdl_hkex_pbmsg.double_2 _DailyIndexLow = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"DailyIndexLow", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_hkex_pbmsg.double_2 DailyIndexLow
    {
      get { return _DailyIndexLow; }
      set { _DailyIndexLow = value; }
    }
    private datayes.mdl.mdl_hkex_pbmsg.double_2 _EstamitedAveragePrice = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"EstamitedAveragePrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_hkex_pbmsg.double_2 EstamitedAveragePrice
    {
      get { return _EstamitedAveragePrice; }
      set { _EstamitedAveragePrice = value; }
    }
    private ulong _IndexTurnover = default(ulong);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"IndexTurnover", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong IndexTurnover
    {
      get { return _IndexTurnover; }
      set { _IndexTurnover = value; }
    }
    private datayes.mdl.mdl_hkex_pbmsg.double_2 _IndexPointChange = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"IndexPointChange", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_hkex_pbmsg.double_2 IndexPointChange
    {
      get { return _IndexPointChange; }
      set { _IndexPointChange = value; }
    }
    private datayes.mdl.mdl_hkex_pbmsg.double_2 _IndexPointChangePercent = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"IndexPointChangePercent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_hkex_pbmsg.double_2 IndexPointChangePercent
    {
      get { return _IndexPointChangePercent; }
      set { _IndexPointChangePercent = value; }
    }
    private uint _UpdateTime = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"UpdateTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint UpdateTime
    {
      get { return _UpdateTime; }
      set { _UpdateTime = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"MID")]
    public enum MID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MessageID", Value=3)]
      MessageID = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SID")]
    public enum SID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceID", Value=11)]
      ServiceID = 11
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"VID")]
    public enum VID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceVersion", Value=101)]
      ServiceVersion = 101
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OMDClosingPrice")]
  public partial class OMDClosingPrice : global::ProtoBuf.IExtensible
  {
    public OMDClosingPrice() {}
    
    private string _TickerSymbol = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"TickerSymbol", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string TickerSymbol
    {
      get { return _TickerSymbol; }
      set { _TickerSymbol = value; }
    }
    private uint _TradTime = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"TradTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint TradTime
    {
      get { return _TradTime; }
      set { _TradTime = value; }
    }
    private datayes.mdl.mdl_hkex_pbmsg.float_3 _ClosingPrice = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ClosingPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_hkex_pbmsg.float_3 ClosingPrice
    {
      get { return _ClosingPrice; }
      set { _ClosingPrice = value; }
    }
    private uint _NumberOfTrades = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"NumberOfTrades", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint NumberOfTrades
    {
      get { return _NumberOfTrades; }
      set { _NumberOfTrades = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"MID")]
    public enum MID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MessageID", Value=4)]
      MessageID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SID")]
    public enum SID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceID", Value=11)]
      ServiceID = 11
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"VID")]
    public enum VID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceVersion", Value=101)]
      ServiceVersion = 101
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MDLHKEXServiceVersion")]
    public enum MDLHKEXServiceVersion
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MDLVID_MDL_HKEX", Value=101)]
      MDLVID_MDL_HKEX = 101
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MDLHKEXMessageID")]
    public enum MDLHKEXMessageID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MDLMID_MDL_HKEX_OMDMarketData", Value=2)]
      MDLMID_MDL_HKEX_OMDMarketData = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MDLMID_MDL_HKEX_HangSengIndex", Value=3)]
      MDLMID_MDL_HKEX_HangSengIndex = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MDLMID_MDL_HKEX_OMDClosingPrice", Value=4)]
      MDLMID_MDL_HKEX_OMDClosingPrice = 4
    }
  
}