// Generated by the code_gen tool.  DO NOT EDIT!
// source: C:/SVN/project/mdl/src/resource/mdl_hkex_msg.xml
// time: 2015/07/04 15:32:55

#pragma once

#include "mdl_api_types.h"

namespace datayes {
namespace mdl {
namespace mdl_hkex_msg {

static const uint16_t MDLVID_MDL_HKEX = 101;

enum MDL_HKEXMessageID {
	MDLMID_MDL_HKEX_OMDMarketData = 2,
	MDLMID_MDL_HKEX_HangSengIndex = 3,
	MDLMID_MDL_HKEX_OMDClosingPrice = 4
};

#pragma pack(1)

struct OMDMarketData {
	enum {
		ServiceID = MDLSID_MDL_HKEX,
		ServiceVer = MDLVID_MDL_HKEX,
		MessageID = MDLMID_MDL_HKEX_OMDMarketData
	};
	MDLAnsiString TickerSymbol;
	MDLTime TradTime;
	int32_t TradStatus;
	int32_t TradType;
	MDLFloatT<3> PreClosePrice;
	MDLFloatT<3> OpenPrice;
	MDLFloatT<3> HighPrice;
	MDLFloatT<3> LowPrice;
	MDLFloatT<3> LastPrice;
	MDLFloatT<3> NominalPrice;
	MDLFloatT<3> VWAP;
	MDLFloatT<3> Change;
	MDLFloatT<5> ChangePct;
	uint64_t Quantity;
	MDLDoubleT<3> Turnover;
	uint32_t NumTrade;
	MDLAnsiString CurrencyCode;
	MDLFloatT<3> Yield;
	MDLFloatT<3> IEP;
	uint64_t AggQty;
	uint32_t TradSessionID;
	uint32_t TradSessionSubID;
	uint32_t TradSessionStatus;
	struct BidBookItem {
		uint64_t Volume;
		MDLFloatT<3> Price;
	};
	MDLListT<BidBookItem> BidBook;
	struct AskBookItem {
		uint64_t Volume;
		MDLFloatT<3> Price;
	};
	MDLListT<AskBookItem> AskBook;
};

struct HangSengIndex {
	enum {
		ServiceID = MDLSID_MDL_HKEX,
		ServiceVer = MDLVID_MDL_HKEX,
		MessageID = MDLMID_MDL_HKEX_HangSengIndex
	};
	uint32_t IndexType;
	uint32_t SecNo;
	uint32_t Status;
	MDLDoubleT<2> CurrentIndex;
	MDLDoubleT<2> DailyIndexHigh;
	MDLDoubleT<2> DailyIndexLow;
	MDLDoubleT<2> EstamitedAveragePrice;
	uint64_t IndexTurnover;
	MDLDoubleT<2> IndexPointChange;
	MDLDoubleT<2> IndexPointChangePercent;
	MDLTime UpdateTime;
};

struct OMDClosingPrice {
	enum {
		ServiceID = MDLSID_MDL_HKEX,
		ServiceVer = MDLVID_MDL_HKEX,
		MessageID = MDLMID_MDL_HKEX_OMDClosingPrice
	};
	MDLAnsiString TickerSymbol;
	MDLTime TradTime;
	MDLFloatT<3> ClosingPrice;
	uint32_t NumberOfTrades;
};

#pragma pack()

} // namespace mdl_hkex_msg
} // namespace mdl
} // namespace datayes
