// Generated by the code_gen tool.  DO NOT EDIT!
// source: C:/SVN/project/mdl/src/resource/mdl_swg_msg.xml
// time: 2015/07/04 15:32:55

#pragma once

#include "mdl_api_types.h"

namespace datayes {
namespace mdl {
namespace mdl_swg_msg {

static const uint16_t MDLVID_MDL_SWG = 101;

enum MDL_SWGMessageID {
	MDLMID_MDL_SWG_Index = 1
};

#pragma pack(1)

struct Index {
	enum {
		ServiceID = MDLSID_MDL_SWG,
		ServiceVer = MDLVID_MDL_SWG,
		MessageID = MDLMID_MDL_SWG_Index
	};
	MDLAnsiString SecurityID;
	MDLUTF8String SecurityName;
	MDLFloatT<3> PreCloPrice;
	MDLFloatT<3> OpenPrice;
	uint64_t Turnover;
	MDLFloatT<3> HighPrice;
	MDLFloatT<3> LowPrice;
	MDLFloatT<3> LastPrice;
	MDLFloatT<3> Ratio;
	uint64_t Volume;
	uint64_t BidVolume123;
	MDLFloatT<3> BidPrice2;
	uint64_t BidVolume2;
	MDLFloatT<3> BidPrice3;
	uint64_t BidVolume3;
	uint64_t AskVolume123;
	MDLFloatT<3> AskPrice2;
	uint64_t AskVolume2;
	MDLFloatT<3> AskPrice3;
	uint64_t AskVolume3;
	MDLTime UpdateTime;
};

#pragma pack()

} // namespace mdl_swg_msg
} // namespace mdl
} // namespace datayes
