// Generated by the code_gen tool.  DO NOT EDIT!
// source: C:/SVN/project/mdl/src/resource/mdl_sys_msg.xml
// time: 2015/07/04 15:32:56

#pragma once

#include "mdl_api_types.h"

namespace datayes {
namespace mdl {
namespace mdl_sys_msg {

static const uint16_t MDLVID_MDL_SYS = 101;

enum MDL_SYSMessageID {
	MDLMID_MDL_SYS_LogonResponse = 2
};

#pragma pack(1)

struct LogonResponse {
	enum {
		ServiceID = MDLSID_MDL_SYS,
		ServiceVer = MDLVID_MDL_SYS,
		MessageID = MDLMID_MDL_SYS_LogonResponse
	};
	MDLAnsiString UserName;
	MDLAnsiString Password;
	struct ServicesItem {
		uint32_t ServiceID;
		uint32_t ServiceVersion;
		struct MessagesItem {
			uint32_t MessageID;
			uint32_t MessageStatus;
		};
		MDLListT<MessagesItem> Messages;
	};
	MDLListT<ServicesItem> Services;
	uint32_t ReturnCode;
};

#pragma pack()

} // namespace mdl_sys_msg
} // namespace mdl
} // namespace datayes
