//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input/mdl_szl1_msg.proto
namespace datayes.mdl.mdl_szl1_pbmsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"double_3")]
  public partial class double_3 : global::ProtoBuf.IExtensible
  {
    public double_3() {}
    
    private long _Value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long Value
    {
      get { return _Value; }
      set { _Value = value; }
    }
    private uint _DecimalShift = (uint)1000;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"DecimalShift", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)1000)]
    public uint DecimalShift
    {
      get { return _DecimalShift; }
      set { _DecimalShift = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"float_3")]
  public partial class float_3 : global::ProtoBuf.IExtensible
  {
    public float_3() {}
    
    private int _Value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Value
    {
      get { return _Value; }
      set { _Value = value; }
    }
    private uint _DecimalShift = (uint)1000;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"DecimalShift", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)1000)]
    public uint DecimalShift
    {
      get { return _DecimalShift; }
      set { _DecimalShift = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SZL1Index")]
  public partial class SZL1Index : global::ProtoBuf.IExtensible
  {
    public SZL1Index() {}
    
    private string _IndexID = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"IndexID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string IndexID
    {
      get { return _IndexID; }
      set { _IndexID = value; }
    }
    private string _IndexName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"IndexName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string IndexName
    {
      get { return _IndexName; }
      set { _IndexName = value; }
    }
    private datayes.mdl.mdl_szl1_pbmsg.double_3 _PreCloseIndex = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"PreCloseIndex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_szl1_pbmsg.double_3 PreCloseIndex
    {
      get { return _PreCloseIndex; }
      set { _PreCloseIndex = value; }
    }
    private datayes.mdl.mdl_szl1_pbmsg.double_3 _OpenIndex = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"OpenIndex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_szl1_pbmsg.double_3 OpenIndex
    {
      get { return _OpenIndex; }
      set { _OpenIndex = value; }
    }
    private datayes.mdl.mdl_szl1_pbmsg.double_3 _HighIndex = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"HighIndex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_szl1_pbmsg.double_3 HighIndex
    {
      get { return _HighIndex; }
      set { _HighIndex = value; }
    }
    private datayes.mdl.mdl_szl1_pbmsg.double_3 _LowIndex = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"LowIndex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_szl1_pbmsg.double_3 LowIndex
    {
      get { return _LowIndex; }
      set { _LowIndex = value; }
    }
    private datayes.mdl.mdl_szl1_pbmsg.double_3 _LastIndex = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"LastIndex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_szl1_pbmsg.double_3 LastIndex
    {
      get { return _LastIndex; }
      set { _LastIndex = value; }
    }
    private datayes.mdl.mdl_szl1_pbmsg.double_3 _TradVolume = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"TradVolume", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_szl1_pbmsg.double_3 TradVolume
    {
      get { return _TradVolume; }
      set { _TradVolume = value; }
    }
    private datayes.mdl.mdl_szl1_pbmsg.double_3 _Turnover = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"Turnover", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_szl1_pbmsg.double_3 Turnover
    {
      get { return _Turnover; }
      set { _Turnover = value; }
    }
    private uint _UpdateTime = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"UpdateTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint UpdateTime
    {
      get { return _UpdateTime; }
      set { _UpdateTime = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"MID")]
    public enum MID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MessageID", Value=1)]
      MessageID = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SID")]
    public enum SID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceID", Value=5)]
      ServiceID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"VID")]
    public enum VID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceVersion", Value=101)]
      ServiceVersion = 101
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SZL1Stock")]
  public partial class SZL1Stock : global::ProtoBuf.IExtensible
  {
    public SZL1Stock() {}
    
    private string _SecurityID = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"SecurityID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SecurityID
    {
      get { return _SecurityID; }
      set { _SecurityID = value; }
    }
    private string _SecurityName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SecurityName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SecurityName
    {
      get { return _SecurityName; }
      set { _SecurityName = value; }
    }
    private datayes.mdl.mdl_szl1_pbmsg.float_3 _PreCloPrice = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"PreCloPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_szl1_pbmsg.float_3 PreCloPrice
    {
      get { return _PreCloPrice; }
      set { _PreCloPrice = value; }
    }
    private datayes.mdl.mdl_szl1_pbmsg.float_3 _OpenPrice = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"OpenPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_szl1_pbmsg.float_3 OpenPrice
    {
      get { return _OpenPrice; }
      set { _OpenPrice = value; }
    }
    private datayes.mdl.mdl_szl1_pbmsg.double_3 _Turnover = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Turnover", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_szl1_pbmsg.double_3 Turnover
    {
      get { return _Turnover; }
      set { _Turnover = value; }
    }
    private uint _TurnNum = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"TurnNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint TurnNum
    {
      get { return _TurnNum; }
      set { _TurnNum = value; }
    }
    private datayes.mdl.mdl_szl1_pbmsg.float_3 _HighPrice = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"HighPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_szl1_pbmsg.float_3 HighPrice
    {
      get { return _HighPrice; }
      set { _HighPrice = value; }
    }
    private datayes.mdl.mdl_szl1_pbmsg.float_3 _LowPrice = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"LowPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_szl1_pbmsg.float_3 LowPrice
    {
      get { return _LowPrice; }
      set { _LowPrice = value; }
    }
    private datayes.mdl.mdl_szl1_pbmsg.float_3 _LastPrice = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"LastPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_szl1_pbmsg.float_3 LastPrice
    {
      get { return _LastPrice; }
      set { _LastPrice = value; }
    }
    private datayes.mdl.mdl_szl1_pbmsg.float_3 _PE1 = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"PE1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_szl1_pbmsg.float_3 PE1
    {
      get { return _PE1; }
      set { _PE1 = value; }
    }
    private datayes.mdl.mdl_szl1_pbmsg.float_3 _PE2 = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"PE2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_szl1_pbmsg.float_3 PE2
    {
      get { return _PE2; }
      set { _PE2 = value; }
    }
    private datayes.mdl.mdl_szl1_pbmsg.float_3 _AskPrice5 = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"AskPrice5", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_szl1_pbmsg.float_3 AskPrice5
    {
      get { return _AskPrice5; }
      set { _AskPrice5 = value; }
    }
    private ulong _AskVolume5 = default(ulong);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"AskVolume5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong AskVolume5
    {
      get { return _AskVolume5; }
      set { _AskVolume5 = value; }
    }
    private datayes.mdl.mdl_szl1_pbmsg.float_3 _AskPrice4 = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"AskPrice4", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_szl1_pbmsg.float_3 AskPrice4
    {
      get { return _AskPrice4; }
      set { _AskPrice4 = value; }
    }
    private ulong _AskVolume4 = default(ulong);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"AskVolume4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong AskVolume4
    {
      get { return _AskVolume4; }
      set { _AskVolume4 = value; }
    }
    private datayes.mdl.mdl_szl1_pbmsg.float_3 _AskPrice3 = null;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"AskPrice3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_szl1_pbmsg.float_3 AskPrice3
    {
      get { return _AskPrice3; }
      set { _AskPrice3 = value; }
    }
    private ulong _AskVolume3 = default(ulong);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"AskVolume3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong AskVolume3
    {
      get { return _AskVolume3; }
      set { _AskVolume3 = value; }
    }
    private datayes.mdl.mdl_szl1_pbmsg.float_3 _AskPrice2 = null;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"AskPrice2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_szl1_pbmsg.float_3 AskPrice2
    {
      get { return _AskPrice2; }
      set { _AskPrice2 = value; }
    }
    private ulong _AskVolume2 = default(ulong);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"AskVolume2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong AskVolume2
    {
      get { return _AskVolume2; }
      set { _AskVolume2 = value; }
    }
    private datayes.mdl.mdl_szl1_pbmsg.float_3 _AskPrice1 = null;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"AskPrice1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_szl1_pbmsg.float_3 AskPrice1
    {
      get { return _AskPrice1; }
      set { _AskPrice1 = value; }
    }
    private ulong _AskVolume1 = default(ulong);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"AskVolume1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong AskVolume1
    {
      get { return _AskVolume1; }
      set { _AskVolume1 = value; }
    }
    private datayes.mdl.mdl_szl1_pbmsg.float_3 _BidPrice1 = null;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"BidPrice1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_szl1_pbmsg.float_3 BidPrice1
    {
      get { return _BidPrice1; }
      set { _BidPrice1 = value; }
    }
    private ulong _BidVolume1 = default(ulong);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"BidVolume1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong BidVolume1
    {
      get { return _BidVolume1; }
      set { _BidVolume1 = value; }
    }
    private datayes.mdl.mdl_szl1_pbmsg.float_3 _BidPrice2 = null;
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"BidPrice2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_szl1_pbmsg.float_3 BidPrice2
    {
      get { return _BidPrice2; }
      set { _BidPrice2 = value; }
    }
    private ulong _BidVolume2 = default(ulong);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"BidVolume2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong BidVolume2
    {
      get { return _BidVolume2; }
      set { _BidVolume2 = value; }
    }
    private datayes.mdl.mdl_szl1_pbmsg.float_3 _BidPrice3 = null;
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"BidPrice3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_szl1_pbmsg.float_3 BidPrice3
    {
      get { return _BidPrice3; }
      set { _BidPrice3 = value; }
    }
    private ulong _BidVolume3 = default(ulong);
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"BidVolume3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong BidVolume3
    {
      get { return _BidVolume3; }
      set { _BidVolume3 = value; }
    }
    private datayes.mdl.mdl_szl1_pbmsg.float_3 _BidPrice4 = null;
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"BidPrice4", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_szl1_pbmsg.float_3 BidPrice4
    {
      get { return _BidPrice4; }
      set { _BidPrice4 = value; }
    }
    private ulong _BidVolume4 = default(ulong);
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"BidVolume4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong BidVolume4
    {
      get { return _BidVolume4; }
      set { _BidVolume4 = value; }
    }
    private datayes.mdl.mdl_szl1_pbmsg.float_3 _BidPrice5 = null;
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"BidPrice5", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_szl1_pbmsg.float_3 BidPrice5
    {
      get { return _BidPrice5; }
      set { _BidPrice5 = value; }
    }
    private ulong _BidVolume5 = default(ulong);
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"BidVolume5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong BidVolume5
    {
      get { return _BidVolume5; }
      set { _BidVolume5 = value; }
    }
    private uint _UpdateTime = default(uint);
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"UpdateTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint UpdateTime
    {
      get { return _UpdateTime; }
      set { _UpdateTime = value; }
    }
    private datayes.mdl.mdl_szl1_pbmsg.float_3 _DifPrice1 = null;
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"DifPrice1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_szl1_pbmsg.float_3 DifPrice1
    {
      get { return _DifPrice1; }
      set { _DifPrice1 = value; }
    }
    private datayes.mdl.mdl_szl1_pbmsg.float_3 _DifPrice2 = null;
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"DifPrice2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public datayes.mdl.mdl_szl1_pbmsg.float_3 DifPrice2
    {
      get { return _DifPrice2; }
      set { _DifPrice2 = value; }
    }
    private ulong _OpenInt = default(ulong);
    [global::ProtoBuf.ProtoMember(35, IsRequired = false, Name=@"OpenInt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong OpenInt
    {
      get { return _OpenInt; }
      set { _OpenInt = value; }
    }
    private ulong _Volume = default(ulong);
    [global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"Volume", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Volume
    {
      get { return _Volume; }
      set { _Volume = value; }
    }
    private uint _DeletionIndicator = default(uint);
    [global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"DeletionIndicator", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint DeletionIndicator
    {
      get { return _DeletionIndicator; }
      set { _DeletionIndicator = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"MID")]
    public enum MID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MessageID", Value=2)]
      MessageID = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SID")]
    public enum SID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceID", Value=5)]
      ServiceID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"VID")]
    public enum VID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceVersion", Value=101)]
      ServiceVersion = 101
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MDLSZL1ServiceVersion")]
    public enum MDLSZL1ServiceVersion
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MDLVID_MDL_SZL1", Value=101)]
      MDLVID_MDL_SZL1 = 101
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MDLSZL1MessageID")]
    public enum MDLSZL1MessageID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MDLMID_MDL_SZL1_SZL1Index", Value=1)]
      MDLMID_MDL_SZL1_SZL1Index = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MDLMID_MDL_SZL1_SZL1Stock", Value=2)]
      MDLMID_MDL_SZL1_SZL1Stock = 2
    }
  
}